// <auto-generated />
namespace TomaszDyskoLab4Zad1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dOCUMENTSMODELANDRELATIONS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dOCUMENTSMODELANDRELATIONS));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031055225_dOCUMENTS MODEL AND RELATIONS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
